title: Rodrigo Oliveira
logo: "/images/logo.png?raw=true"
description: >
  Data Scientist at Unimed Blumenau
  <br><br>
  Provide data-driven solutions and business problem solving through Data Engineering, Artificial Intelligence and Machine Learning.
  <br><br>
  <a href="https://www.linkedin.com/in/rodrigolima82/">View My LinkedIn Profile</a> 


theme: jekyll-theme-minimal
google_analytics: UA-159543171-1
