title: Rodrigo Oliveira
logo: "/images/logo.png?raw=true"
description: >
  Data Scientist at Unimed Blumenau
  <br><br>
  Fornecer soluções orientadas a dados e resolução de problemas de negócios através do uso de ferramentas de 
  Engenharia de Dados, Inteligência Artificial, Machine Learning e Deep Learning. 
  <br><br>
  <a href="https://www.linkedin.com/in/rodrigolima82/">View My LinkedIn Profile</a> 


theme: jekyll-theme-minimal
google_analytics: UA-159543171-1
