title: Rodrigo Lima # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist at Unimed Blumenau
  <br><br>
  Fornecer soluções orientadas a dados e resolução de problemas de negócios desafiadores através da Engenharia de Dados, Inteligência Artificial, Machine Learning (aprendizado de máquina) e Deep Learning. 
  <br><br>
  <a href="https://www.linkedin.com/in/rodrigolima82/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
